using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ItchioLibrary.Models
{
	public class Collection
	{
		/// <summary>
		/// Site-wide unique identifier generated by itch.io
		/// </summary>
		public long id;
		/// <summary>
		/// Human-friendly title (may contain any character)
		/// </summary>
		public string title;
		/// <summary>
		/// Date the collection was created
		/// </summary>
		public DateTime createdAt;
		/// <summary>
		/// Date this collection was last updated at
		/// </summary>
		public DateTime updatedAt;
		/// <summary>
		/// Count of the games in this collection
		/// </summary>
		public long gamesCount;
		/// <summary>
		/// Identifier of the itch.io user to which this collection belongs
		/// </summary>
		public long userId;
	}
}
